app/app.gradle, app/src/main/java/com/shifthackz/aisdv1/app/di/ProvidersModule.kt, core/common/src/main/java/com/shifthackz/aisdv1/core/common/appbuild/BuildInfoProvider.kt, core/common/src/main/java/com/shifthackz/aisdv1/core/common/appbuild/BuildType.kt, core/common/src/main/java/com/shifthackz/aisdv1/core/common/links/LinksProvider.kt, core/common/src/main/java/com/shifthackz/aisdv1/core/common/schedulers/SchedulersExtensions.kt, core/ui/src/main/java/com/shifthackz/aisdv1/core/extensions/UriExtensions.kt, gradle/dependencies.gradle, presentation/presentation.gradle, presentation/src/main/java/com/shifthackz/aisdv1/presentation/activity/AiStableDiffusionActivity.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/di/PresentationModule.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/features/ImagePickerFeature.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/features/InAppReviewFeature.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/home/HomeNavigationGraph.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsContract.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsStateProducer.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/setup/ServerSetupViewModel.kt, presentation/src/main/res/values-uk/strings.xml, presentation/src/main/res/values/strings.xml
=> Ukrainian localization

build.gradle, gradle.properties, gradle/common.gradle, gradle/wrapper/gradle-wrapper.properties
- Migrate gradle wrapper version to `8.0.0`
=> Gradle migration to 8.0.0

build.gradle, core/ui/build.gradle, presentation/presentation.gradle
- Gradle = 8.0.1
- Kotlin = 1.8.21
- Compose Compiler = 1.4.7
=> Upgrade project dependencies

core/common/src/main/java/com/shifthackz/aisdv1/core/common/extensions/StringExtensions.kt
=> Hotfix for 'fixUrlSlashes'

app/app.gradle, app/src/main/res/values/strings.xml
=> Separate package for FOSS

data/src/main/java/com/shifthackz/aisdv1/data/preference/PreferenceManagerImpl.kt, domain/src/main/java/com/shifthackz/aisdv1/domain/entity/Settings.kt, domain/src/main/java/com/shifthackz/aisdv1/domain/preference/PreferenceManager.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/core/GenerationMviState.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/core/GenerationMviViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/features/AnalyticsEvents.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/img2img/ImageToImageContract.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/img2img/ImageToImageScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/img2img/ImageToImageViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsContract.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsStateProducer.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/txt2img/TextToImageContract.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/txt2img/TextToImageScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/txt2img/TextToImageViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/widget/input/GenerationInputForm.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/widget/item/SettingsItem.kt, presentation/src/main/res/values-uk/strings.xml, presentation/src/main/res/values/strings.xml
=> Generation form redesign

core/ui/build.gradle, core/ui/src/main/java/com/shifthackz/aisdv1/core/ui/MviExtensions.kt, gradle/dependencies.gradle, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/gallery/detail/GalleryDetailScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/gallery/list/GalleryScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/img2img/ImageToImageScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/loader/ConfigurationLoaderScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/setup/ServerSetupScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/txt2img/TextToImageScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/widget/coins/AvailableCoinsComposable.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/widget/connectivity/ConnectivityComposable.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/widget/motd/MotdComposable.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/widget/version/VersionCheckerComposable.kt
- Collecting all MVI states considering lifecycle
=> MVI Lifecycle

app/build.gradle, build.gradle, core/common/src/main/java/com/shifthackz/aisdv1/core/common/appbuild/BuildVersion.kt, data/src/main/java/com/shifthackz/aisdv1/data/mappers/ImageToImagePayloadMappers.kt, data/src/main/java/com/shifthackz/aisdv1/data/mappers/ResponseParamsMapper.kt, data/src/main/java/com/shifthackz/aisdv1/data/mappers/ServerConfigurationMappers.kt, data/src/main/java/com/shifthackz/aisdv1/data/mappers/StableDiffusionModelsMappers.kt, data/src/main/java/com/shifthackz/aisdv1/data/mappers/StableDiffusionSamplersMappers.kt, data/src/main/java/com/shifthackz/aisdv1/data/mappers/TextToImagePayloadMappers.kt, data/src/main/java/com/shifthackz/aisdv1/data/remote/AppVersionRemoteDataSource.kt, data/src/main/java/com/shifthackz/aisdv1/data/remote/HordeGenerationRemoteDataSource.kt, network/src/main/java/com/shifthackz/aisdv1/network/api/sdai/DownloadableModelsRestApiImpl.kt, network/src/main/java/com/shifthackz/aisdv1/network/model/ServerConfigurationRaw.kt, network/src/main/java/com/shifthackz/aisdv1/network/model/StableDiffusionModelRaw.kt, network/src/main/java/com/shifthackz/aisdv1/network/model/StableDiffusionSamplerRaw.kt, network/src/main/java/com/shifthackz/aisdv1/network/response/AppVersionResponse.kt, network/src/main/java/com/shifthackz/aisdv1/network/response/DownloadableModelResponse.kt, network/src/main/java/com/shifthackz/aisdv1/network/response/HordeGenerationCheckResponse.kt, network/src/main/java/com/shifthackz/aisdv1/network/response/HordeUserResponse.kt, network/src/main/java/com/shifthackz/aisdv1/network/response/SdGenerationResponse.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsScreen.kt, storage/src/main/java/com/shifthackz/aisdv1/storage/di/DatabaseModule.kt
- Api backward compatibility improvements
=> Api backward compatibility improvements :: Patch 1

core/validation/src/main/java/com/shifthackz/aisdv1/core/validation/dimension/DimensionValidatorImpl.kt
- Fixed the maximum size so it's able to generate up to 2048 px in width/height.
- Also fixed the wrong error message that got displayed.
- None
=> Fixed Maximum Size

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values/themes.xml, app/src/main/res/xml/locale_config.xml, presentation/build.gradle, presentation/src/main/java/com/shifthackz/aisdv1/presentation/activity/AiStableDiffusionActivity.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/modal/ModalRenderer.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/modal/language/LanguageBottomSheet.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/model/Modal.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsIntent.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/utils/Constants.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/widget/item/SettingsItem.kt, presentation/src/main/res/values-ru/strings.xml, presentation/src/main/res/values-tr/strings.xml, presentation/src/main/res/values-uk/strings.xml, presentation/src/main/res/values/strings.xml
- Implement new android api for system localization
- Implement in-app language picker
Documentation: [https://developer.android.com/guide/topics/resources/app-languages](https://developer.android.com/guide/topics/resources/app-languages)
=> Localization settings

data/src/main/java/com/shifthackz/aisdv1/data/preference/PreferenceManagerImpl.kt
=> Fix Preference observer

data/src/main/java/com/shifthackz/aisdv1/data/preference/PreferenceManagerImpl.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/core/GenerationFormUpdateEvent.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/core/GenerationMviViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/navigation/NavigationEffect.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/navigation/graph/DrawerNavGraph.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/navigation/graph/HomeNavGraph.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/navigation/router/home/HomeRouter.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/navigation/router/home/HomeRouterImpl.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/drawer/DrawerScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/gallery/detail/GalleryDetailViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/home/HomeNavigationIntent.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/home/HomeNavigationScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/home/HomeNavigationViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/img2img/ImageToImageViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/txt2img/TextToImageViewModel.kt, presentation/src/main/res/values/strings.xml, presentation/src/test/java/com/shifthackz/aisdv1/presentation/core/CoreGenerationMviViewModelTest.kt, presentation/src/test/java/com/shifthackz/aisdv1/presentation/screen/gallery/detail/GalleryDetailViewModelTest.kt
=> Internal navigation fix

presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/setup/ServerSetupViewModel.kt, presentation/src/main/res/values-ru/strings.xml, presentation/src/test/java/com/shifthackz/aisdv1/presentation/screen/setup/ServerSetupViewModelTest.kt
- Implements parallel downloads for Local Diffusion models on Configuration screen
=> Local Diffusion models parallel downloads

core/localization/src/main/res/values-ru/strings.xml, core/localization/src/main/res/values-tr/strings.xml, core/localization/src/main/res/values-uk/strings.xml, core/localization/src/main/res/values-zh/strings.xml, core/localization/src/main/res/values/strings.xml, data/src/main/java/com/shifthackz/aisdv1/data/preference/PreferenceManagerImpl.kt, domain/src/main/java/com/shifthackz/aisdv1/domain/entity/Grid.kt, domain/src/main/java/com/shifthackz/aisdv1/domain/entity/Settings.kt, domain/src/main/java/com/shifthackz/aisdv1/domain/preference/PreferenceManager.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/modal/ModalRenderer.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/modal/grid/GridBottomSheet.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/modal/language/LanguageBottomSheet.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/model/Modal.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/gallery/list/GalleryScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/gallery/list/GalleryState.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/gallery/list/GalleryViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsIntent.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsState.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/widget/item/GridIcon.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/widget/item/SettingsHeader.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/widget/item/SettingsItem.kt, presentation/src/test/java/com/shifthackz/aisdv1/presentation/screen/gallery/list/GalleryViewModelTest.kt
- Gallery Grid size preference
=> Gallery Grid size preference

data/src/main/java/com/shifthackz/aisdv1/data/preference/PreferenceManagerImpl.kt, domain/src/main/java/com/shifthackz/aisdv1/domain/preference/PreferenceManager.kt, feature/work/src/main/java/com/shifthackz/aisdv1/work/task/TextToImageTask.kt
- Handle LocalDiffusion process death in TextToImageTask.kt (Work Manager)
=> Handle LocalDiffusion process death in TextToImageTask.kt (Work Manager)

dependencies.gradle, presentation/build.gradle, presentation/src/main/java/com/shifthackz/aisdv1/presentation/navigation/graph/MainNavGraph.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/setup/ServerSetupScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/setup/ServerSetupScreenTags.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/setup/ServerSetupViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/setup/forms/LocalDiffusionForm.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/setup/mappers/LocalModelMappers.kt, presentation/src/test/java/com/shifthackz/aisdv1/presentation/core/CoreComposeTest.kt, presentation/src/test/java/com/shifthackz/aisdv1/presentation/screen/gallery/detail/GalleryDetailViewModelTest.kt, presentation/src/test/java/com/shifthackz/aisdv1/presentation/screen/setup/ServerSetupScreenTest.kt, presentation/src/test/java/com/shifthackz/aisdv1/presentation/screen/setup/ServerSetupViewModelTest.kt, presentation/src/test/java/com/shifthackz/aisdv1/presentation/utils/ComposeTestUtils.kt
- Implemented compose unit test libraries
=> Compose unit test

.github/workflows/android_test.yml, app/build.gradle, presentation/src/main/java/com/shifthackz/aisdv1/presentation/modal/tag/EditTagDialog.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/modal/tag/EditTagEffect.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/modal/tag/EditTagIntent.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/modal/tag/EditTagState.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/modal/tag/EditTagViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/utils/Constants.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/widget/input/GenerationInputForm.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/widget/input/SliderTextInputField.kt
- Combined slider / text / increment / decrement double UI inputs
=> Combined slider / text / increment / decrement double UI inputs

core/ui/src/main/java/com/shifthackz/aisdv1/core/extensions/GestureExtensions.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/di/ViewModelModule.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/loader/ConfigurationLoaderScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/onboarding/OnBoardingScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/onboarding/OnBoardingState.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/onboarding/OnBoardingViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/onboarding/page/FormPageContent.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/onboarding/page/LocalDiffusionPageContent.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/onboarding/page/LookAndFeelPageContent.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/onboarding/page/ProvidersPageContent.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/settings/SettingsScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/splash/SplashScreen.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/txt2img/TextToImageScreen.kt, presentation/src/test/java/com/shifthackz/aisdv1/presentation/screen/onboarding/OnBoardingViewModelSplashSourceTest.kt, presentation/src/test/java/com/shifthackz/aisdv1/presentation/screen/setup/ServerSetupViewModelTest.kt
Onboarding UI update
- Added onboarding form page animation 
- Made other pages animations run only when page is visible for the user
=> Onboarding UI update

presentation/src/main/java/com/shifthackz/aisdv1/presentation/activity/AiStableDiffusionActivity.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/activity/AiStableDiffusionViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/activity/AppIntent.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/activity/AppState.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/navigation/router/main/MainRouterImpl.kt, presentation/src/test/java/com/shifthackz/aisdv1/presentation/activity/AiStableDiffusionViewModelTest.kt
- Updated splash screen logic & animation
- Fixed ServerSetup back navigation bug
=> Splash screen update

core/ui/src/main/java/com/shifthackz/aisdv1/core/ui/MviComponent.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/onboarding/OnBoardingScreen.kt
=> StatusBar Fix

presentation/src/main/java/com/shifthackz/aisdv1/presentation/di/ViewModelModule.kt
=> Koin 4.0.0 migration

.gitignore, app/build.gradle.kts, build-logic/convention/src/main/kotlin/ApplicationConventionPlugin.kt, build-logic/convention/src/main/kotlin/com/shifthackz/aisdv1/buildlogic/Android.kt, build.gradle.kts, gradle/libs.versions.toml, network/src/main/java/com/shifthackz/aisdv1/network/di/NetworkModule.kt, storage/build.gradle.kts
=> Kapt to Ksp migration

presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/setup/components/ConfigurationModeButton.kt
- Updated ConfigurationModeButton title text alignment
=> Onboarding Ui fix

data/build.gradle.kts, data/src/main/java/com/shifthackz/aisdv1/data/preference/PreferenceManagerImpl.kt, data/src/test/java/com/shifthackz/aisdv1/data/preference/PreferenceManagerImplTest.kt, domain/src/main/java/com/shifthackz/aisdv1/domain/preference/PreferenceManager.kt, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/home/HomeNavigationViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/theme/global/AiSdAppThemeState.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/theme/global/AiSdAppThemeViewModel.kt
=> SharedPreferences refactor 

core/localization/src/main/res/values-zh/strings.xml
- Corrected Chinese translation typos
- Reorganized and retranslated some texts to improve readability
=> docs: fix translation typos and improve quality

core/localization/src/main/res/values-zh/strings.xml
- Remove duplicated translatable strings in values-zh/strings.xml
=> Remove duplicated translatable strings in values-zh/strings.xml

presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/report/ReportViewModel.kt
- Simplify playstore reporting
=> Simplify playstore reporting

core/ui/src/main/java/com/shifthackz/aisdv1/core/extensions/ComposableExtensions.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/donate/DonateScreen.kt
- Added fadedEdge compose extension
=> Donation screen UI update

app/build.gradle.kts, gradle/libs.versions.toml
- Exclude dependencies info blob from APK/AAB binary
=> Exclude dependencies info blob from APK/AAB binary

app/build.gradle.kts, app/src/playstore/AndroidManifest.xml
- Force exclude "android.permission.READ_MEDIA_IMAGES" permission
=> Force exclude "android.permission.READ_MEDIA_IMAGES" permission

build-logic/settings.gradle.kts, gradle/wrapper/gradle-wrapper.properties
- Migrate to gradle 8.11.1 binary
=> Migrate to gradle 8.11.1 binary

presentation/src/main/java/com/shifthackz/aisdv1/presentation/core/GenerationMviViewModel.kt, presentation/src/main/java/com/shifthackz/aisdv1/presentation/screen/setup/components/ConfigurationModeButton.kt
=> Migrate to Kotlin 2.1.20

docs/mediapipe.json, docs/models.json
- Add gh-proxy mirror to ONNX and MediaPipe model link sources
=> Add gh-proxy mirror to ONNX and MediaPipe model link sources

docs/mediapipe.json
-  Add share.moroz.cc mirror to MediaPipe model link sources
=>  Add share.moroz.cc mirror to MediaPipe model link sources

docs/models.json
-  Add share.moroz.cc mirror to ONNX model link sources
=>  Add share.moroz.cc mirror to ONNX model link sources
